sudo: false 

language: python
    - 3.5
install: 
    -pip install codecov
    
scripy:
    
    - coverage run pokermidterm16.py
    
after_success:
    
     - bash <(curl -s https://codecov.io/bash)
